### ISSUE TITLE
Указание валюты

### ISSUE THREAD

**Issue by t3mp14r3** [t3mp14r3/mensarius#1]
Стоит ли отдельно хранить валюту для каждого расхода?

Таким образом, например, можно в одной книге хранить записи о тратах в рублях и в долларах одновременно.

Но не является ли это ненужным перегрузом?

**Comment by Rubedo-73** [comment]
можно, но расчет не нужно пересчитывать на текущий курс, переусложнение уже будет точно

**Comment by t3mp14r3** [comment]
> можно, но расчет не нужно пересчитывать на текущий курс, переусложнение уже будет точно

Именно, вопрос еще в том, как выводить статистику, без курса, чтобы не было проблем. Я думаю пока, в этом случае разделять на валюты, например:

Spent: 200R
Spent: 100$

Не суммировать разные расходы с разными валютами, а только с одинаковыми

**Comment by Rubedo-73** [comment]
я думаю вопрос в трате средств разных валют может быть пререоценен, пусть юудет возможность выбора валюты и установки ее по умолчанию, суммы имхо легче вывести по соответствующим валютам и не более

**Comment by t3mp14r3** [comment]
Хорошо
