### ISSUE TITLE
Основаная билбиотека для разработки

### ISSUE THREAD

**Issue by qlofly** [t3mp14r3/mensarius#3]
Мне кажется, что для более удобной разработки было бы неплохо использовать какую-то одну либу. 
Из популярных можно выделить эти:

- [Fire](https://github.com/google/python-fire)
- [Click](https://palletsprojects.com/p/click/)
- [Cleo](https://github.com/marknotfound/cleo)
- [Cement](https://docs.builtoncement.com/)

Подробнее о них описывается на [хабре](https://habr.com/ru/post/466999/).
 На англоязычных сайтах (да и вообще много где) часто нахваливают Click. Собственно можно начать работу с этой библиотеки, либо же рассмотреть другие варианты.

**Comment by t3mp14r3** [comment]
Я понял в чем идея и источник беспокойства.

Если бы у нас был one-line интерфейс, как например у утилит cat и grep, это бы имело смысл, так как надо фильтровать все флаги и параметры.

Но я думал про полноценный интерфейс, то есть, ты запускаешь программу и делаешь что-то внутри, как vim или htop, там внутри будет интерфейс, где будут вопросы, данные, подсказки, инпут пользователя и тд. Такой подход, на мой взгляд, упростит взаимодействие, не надо будет выучивать кучу комманд, все будет внутри интерфейса.

Поэтому, мне кажется, что лучше не нагружаться доп либами и ограничиться обычными print и input, если их будет недостаточно, просто описать пару функций, которые упростят вывод чего-то сложного.

Жду критики :)

**Comment by qlofly** [comment]
А твой вариант мне больше нравится)
Изначально у меня просто не было представления как мы будем это реализовывать, сейчас потихоньку вырисовывается вся картина
