### ISSUE TITLE
Проблема с поддержкой массивов

### ISSUE THREAD

**Issue by t3mp14r3** [t3mp14r3/mensarius#4]
Из-за перехода с JSON на SQLite появилась проблемка, нужно хранить массивы, а их нету.

Остается два варианта:
+ Делать строку, а потом из нее вытягивать данные
+ Делать отдельную таблицу по всем правилам бд

Оба варианта валидны и имеют свои плюсы/минусы, какие мысли?

**Comment by Rubedo-73** [comment]
ну можно вернуться к json, тк проект маленький, sqlite конечно я поддержываю но все же считаю проек не настолько большим + нет массивов

**Comment by t3mp14r3** [comment]
К сожалению, парсинг будет утомительно тяжелым, думаю, лучше сделать отдельную таблицу под теги, так можно будет писать, доставать и сортировать без проблем, с json так, к сожалению, не получится
